### ISSUE TITLE
Nice job!

### ISSUE THREAD

**Issue by leerob** [condinoaljoseph/aljoseph.co#41]
This is really nice - great work 😄

**Comment by leerob** [comment]
Make sure you use environment variables for your secrets so others can't use them, btw!

https://github.com/condinoaljoseph/aljoseph.co/blob/master/utils/redis.js#L4-L10

**Comment by einSelbst** [comment]
you could check out https://github.com/Yelp/detect-secrets

**Comment by condinoaljoseph** [comment]
@leerob Thanks for checking it out. I highly appreciate it. Yeah i need to learn how env works on next js. Thanks @leerob .I'm a big fan.

**Comment by condinoaljoseph** [comment]
@einSelbst Thanks man. Highly appreciated. I will check it out
