### ISSUE TITLE
Make the text visible in the text field on dark mode

### ISSUE THREAD

**Issue by Tiansing** [condinoaljoseph/aljoseph.co#49]
![image](https://user-images.githubusercontent.com/59194525/108309026-c4ec3600-71eb-11eb-861f-5ef2fc17d250.png)

I tried to type "sample text" in the text field while on dark mode but the text seems too difficult to see, I think you should change the text color only in the text fields when on dark mode. Besides, it seems there's no issue on light mode. Great work po kuys!. sana gumaling din ako sa ganyang level.

**Comment by condinoaljoseph** [comment]
Thanks kuys. Will do. gagaling ka po lods. let curiousity do the work.
